import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import CartButton from "@/app/components/CartButton";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CameraShop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full p-4 h-100 relative shadow-md bg-[#3F3F3F]">
          <Image
            src='/product-images/default.jpg'
            alt="Header"
            fill
            className="object-cover"
            priority
          />
        </header>
        <NavBar/>

        {children}
        <CartButton/>
      </body>
    </html>
  );
}
