import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import CartButton from "@/app/components/CartButton";
import Image from "next/image";
import AccountButton from "@/app/components/AccountButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CameraShop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full p-4 aspect-5/1 relative shadow-md bg-[#e3e9e9]">
          <Image
            src='/product-images/header.jpg'
            alt="Header"
            fill
            className="object-cover"
            priority
          />
        </header>

        <div className="flex">
          <aside className="w-64 bg-[#172e34] text-white p-6">
            <NavBar />
          </aside>
          <main className="flex-1 p-6 bg-[#172e34] text-gray-950">
            {children}
          </main>
        </div>
        <div className="fixed top-4 right-4 flex gap-6">
          <AccountButton/>
          <CartButton/>
        </div>
      </body>
    </html>
  );
}
